### ISSUE TITLE
enable low_cpu_mem_usage when loading model

### ISSUE THREAD

**Issue by lchu-ibm** [foundation-model-stack/fms-hf-tuning#12]
we should enable low_cpu_mem_usage to avoid loading 8 copies of the model into CPU.  This should boost the memory usage as well as loading time.

@Ssukriti

**Comment by lchu-ibm** [comment]
`from_pretrained (.., low_cpu_mem_usage=True)`

**Comment by ggcr** [comment]
is this working already?

**Comment by fabianlim** [comment]
@lchu-ibm `low_cpu_mem_usage` is already defaulted to `True` when launching with our [accelerate defaults](https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/fixtures/accelerate_fsdp_defaults.yaml#L38). 

As you can see here when `is_fsdp_enabled() = True` , which it will be when that flag is set, then `low_cpu_mem_usage` is set to True
 https://github.com/huggingface/transformers/blob/3f06f95ebe617b192251ef756518690f5bc7ff76/src/transformers/modeling_utils.py#L3442-L3443
