### ISSUE TITLE
Contribute ADR for Acceleration Framework Idea

### ISSUE THREAD

**Issue by Ssukriti** [foundation-model-stack/fms-hf-tuning#144]
## Is your feature request related to a problem? Please describe.

The issue is to discuss and document Design for a  framework to include custom acceleration tools into sft_trainer.py, that improve training metrics such as GPU memory consumption, training speed, etc.

## Describe the solution you'd like
1. Framework for for utilizing libraries of packages that accelerate fine-tuning / training of large models.
2. Design on how to integrate with framework with fms-tuning 
3. Solution for dependency management
4. Design to be reviewed and accepted by maintainers

**Comment by anhuong** [comment]
since the ADR was reviewed and merged and we have since also added fms-acceleration as an optional dep, closing this issue
