### ISSUE TITLE
Upgrade to new transformers raises a flag in flash attention usage

### ISSUE THREAD

**Issue by raghukiran1224** [foundation-model-stack/fms-hf-tuning#16]
The current code is using an older API for attention type. We need to move this to the newer version:

```
The model was loaded with use_flash_attention_2=True, which is deprecated and may be removed in a future release. Please use `attn_implementation="flash_attention_2"` instead.
```

**Comment by Ssukriti** [comment]
@kmehant could you or anyone else from your team take this issue to fix the warning and update the way we use flash attention please? it should eb a quick fix - the. warning is showing up in container logs so we need to fix it

**Comment by kmehant** [comment]
I have raised a PR @Ssukriti here - https://github.com/foundation-model-stack/fms-hf-tuning/pull/101
