### ISSUE TITLE
feat: Allow specifying logging level from the CLI 

### ISSUE THREAD

**Issue by kmehant** [foundation-model-stack/fms-hf-tuning#195]
We should allow for specifying logging level for the user of the CLI interface of fms-hf-tuning. We might introduce a logging level flag to the interface.

**Comment by anhuong** [comment]
Agreed, @tharapalanivel did some investigation in this and found:
> Thara:
> I've set the LOG_LEVEL env var to DEBUG and it changes only the level in `accelerate_launch.py`
> To get the ones in `sft_trainer.py` to work, since that file uses logging from `transformers.utils` , I've had to change:
>  `logger = logging.get_logger("transformers")` [here](https://github.com/foundation-model-stack/fms-hf-tuning/blob/40869c2765543d83b4aba1787e03d78938e1c6f1/tuning/sft_trainer.py#L437)
> and set env var `"TRANSFORMERS_VERBOSITY":"debug"`
>  I think it creates a new logger when you instantiate it for a new file. I looked at this https://huggingface.co/docs/transformers/en/main_classes/logging and I think you need to make sure that the right instance of the logger gets pulled up by passing the name "transformers"
>
> Anh: 
> I also see in https://github.com/huggingface/transformers/blob/main/src/transformers/utils/logging.py#L151 that the `get_logger` maybe isn’t being used properly…This function is not supposed to be directly accessed unless you are writing a custom transformers module.
> So either using generic `logging` or updating to be `logger = logging.get_logger("transformers")` may be better
> 
> Thara:
> I'm up for moving to generic logging although I don't what the actual usecase was for us to start with transformer.utils.logging ages ago

Thus we agree having logging in sft_trainer that is configurable would be useful. And we are up for moving to generic [logging](https://docs.python.org/3/library/logging.html) package

**Comment by Abhishek-TAMU** [comment]
Hi @kmehant,
To confirm again, wanted to ask if setting "logging level" from env var is sufficient or would an additional flag need to be added in argument and parsed in the code ?

CC: @anhuong

**Comment by kmehant** [comment]
@Abhishek-TAMU I think having both the ways should be helpful and can come handy based on the usecases. Thanks.
