### ISSUE TITLE
fix: freeze to specific set of versions with reliable tighter lower and upper bounds.

### ISSUE THREAD

**Issue by kmehant** [foundation-model-stack/fms-hf-tuning#196]
From various collaborations and experience, we faced issues for not having strict version bounds given quickly updating HF dependencies some introducing breaking changes. For instance, there were issues with not freezing to certain versions when we had to start with the existing conda environment and install on top of it. It would be of great help if we can narrow down error surface by having tighter bounds over the versions.

**Comment by VassilisVassiliadis** [comment]
I think this is related to https://github.com/foundation-model-stack/fms-hf-tuning/issues/60

**Comment by kmehant** [comment]
@VassilisVassiliadis Thanks for referencing, will close this once the attached issue is closed as well. Will keep this open for reference related to IL work. Thanks

**Comment by kmehant** [comment]
I think the bounds are being met at this point and being reiterated on breaking changes.
