### ISSUE TITLE
Upgrading to TRL>0.9 Causes Incompatibility with Extended TrainingArguments

### ISSUE THREAD

**Issue by achew010** [foundation-model-stack/fms-hf-tuning#198]
## Describe the bug

Upgrading to version `trl>0.9` throws  `TypeError: SFTConfig.__init__() got an unexpected keyword argument 'cache_dir'` when instantiating SFTConfig with [training arguments](https://github.com/huggingface/trl/blob/974b0d380f12c357b70265c5f2dd2c8cb39a6a3e/trl/trainer/sft_trainer.py#L149). This is due to   the extension of `TrainingArguments` in [fms-hf-tuning](https://github.com/foundation-model-stack/fms-hf-tuning/blob/087e0c47edd26c77e744616a8b233bc617135c37/tuning/config/configs.py#L79).

**Comment by anhuong** [comment]
This should be fixed with the PR that was merged in two ago described in issue #206, sorry for duplicating this issue that already existed for it.
