### ISSUE TITLE
Update trl library past v0.8.6

### ISSUE THREAD

**Issue by anhuong** [foundation-model-stack/fms-hf-tuning#206]
## Is your feature request related to a problem? Please describe.

Upgrading trl to latest version [v0.9.3](https://github.com/huggingface/trl/releases/tag/v0.9.3) released two weeks ago breaks for fms-hf-tuning. Getting error `TypeError: SFTConfig.__init__() got an unexpected keyword argument 'cache_dir'` since this is a param that we added to fms-hf-tuning/config/config.py `TrainingArguments`.

From investigation from @alex-jw-brooks :

> This is not an issue in transformers/trl, the problem is that we have our own class for extending the transformers `TrainingArguments` ([here](https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/tuning/config/configs.py#L78), which very confusingly is also named `TrainingArguments`.
> In newer versions of TRL, they are kwarg expanding the dataclass as a dictionary to init the SFT config ([here](https://github.com/huggingface/trl/blob/main/trl/trainer/sft_trainer.py#L149)), which breaks things because the subclass that we have includes additional fields that are unexpected kwargs in the transformers `TrainingArguments`  / TRL SFT Config (which is a subclass of the transformers `TrainingArguments`, and therefore does not have the fields from our subclass).
> In the past, it looks like this has been passed straight to the HF Trainer, which I assume has weaker validation and is ignoring these fields
>
> So either:
> In our library, we should not pass our subclass through TRL, and should instead build a transformers TrainingArguments, which is probably a good idea anyway
> Or
> TRL should drop fields that are unexpected fields when converting those args to a dict before initializing the SFT config, if that is a behavior they want to support
> 
>  One short and gross way to do the former is something like this:
```
import transformers
import dataclasses
...

# Get the k/v pairs for all of the things in the dict representation of our subclass that are actually part of the transformers TrainingArguments we inherit from
transformer_train_arg_fields = [x.name for x in dataclasses.fields(transformers.TrainingArguments)]
transformer_kwargs = {k: v for k, v in train_args.to_dict().items() if k in transformer_train_arg_fields}

training_args = transformers.TrainingArguments(**transformer_kwargs)

# Then pass that thing to SFT Trainer as `args`
```
> which has a pretty terrible code smell, but minimizes the changes to this part of the code since it is part of an already pretty big PR, which needs to upgrade TRL anyway.
> I do think that in a follow-up we should reconsider having this be a subclass though, it seems like a bit of a strange decision to me since the extra fields are not used in the trainer instance, and I suspect it was written for convenience for the CLI etc
>
> Fabian:
> we could just instead inherit from the new SFTConfig class in trl?
>
> Alex:
> I think we could do that, but we would need to change the class name too, otherwise the check in TRL for `args.__class__.__name__ == "TrainingArguments"` will still try to build a new SFT Config instance 

## Describe the solution you'd like

Investigate how to adjust our `TrainingArguments` so we can update trl library.

**Comment by alex-jw-brooks** [comment]
Link to PR https://github.com/foundation-model-stack/fms-hf-tuning/pull/213
