### ISSUE TITLE
feat: Need to support aync logging in the library to record metadata and logs from execution.

### ISSUE THREAD

**Issue by dushyantbehl** [foundation-model-stack/fms-hf-tuning#215]
## Is your feature request related to a problem? Please describe.

Currently fms-hf-tuning uses transformer logging which can be replaced by async logging library which supports logging metadata  and logs without being tied to upstream modules like tranformers. 

## Describe the solution you'd like

Replace tranformer logging with asyn logger.

cc @ashokponkumar

**Comment by kmehant** [comment]
related and possibly duplicate of - https://github.com/foundation-model-stack/fms-hf-tuning/issues/195 and https://github.com/foundation-model-stack/fms-hf-tuning/issues/194
