### ISSUE TITLE
Performance regression in fms-hf-tuning v1.2.0 image

### ISSUE THREAD

**Issue by albertoperdomo2** [foundation-model-stack/fms-hf-tuning#311]
## Describe the bug
We have observed that in the recent **fms-hf-tuning** release `v1.2.0` there is a very noticeable regression in terms of training runtime for the models that we evaluate in our pipeline. We initially compared the following images: 

- `quay.io/modh/fms-hf-tuning:release-5e4e9441febdb5b2beb21eaecdda1103abd1db05` - `fms-hf-tuning v1.0.0-rc.1`.
- `quay.io/modh/fms-hf-tuning:release-ec50c3d7dc09f50d9885f25efc3d2fc98a379709` - `fms-hf-tuning v1.0.0`.
- `quay.io/modh/fms-hf-tuning:release-014bbf70f020a5ac5e40bfe5fb0285a5d7676a42` - `fms-hf-tuning v1.1.0`.
- `quay.io/modh/fms-hf-tuning:release-d4a201ac1eb3535a38c7f8a25289b085a91ee4ca` - `fms-hf-tuning v1.2.0`.

Additionally, we created two more images that are based on `quay.io/modh/fms-hf-tuning:release-d4a201ac1eb3535a38c7f8a25289b085a91ee4ca` (*v1.2.0*)where we **just** changed the `transformers` version:

- One with Transformers 4.40.0. 
- One with Transformers 4.43.0.

## Platform

Red Hat Openshift AI. 

## Expected behavior

We were expecting - compared to previous versions - higher throughput, lower GPU usage and lower training runtime. 

## Observed behavior

We observed a big degradation in throughput and training runtime, while the GPU usage is as expected. 

### Train runtime
---
![comparison_train_runtime](https://github.com/user-attachments/assets/7cbd0335-62c2-4e51-a5cc-4b6e133e59ca)

### GPU usage
---
![comparison_gpu_total_memory_usage_max](https://github.com/user-attachments/assets/622b65c0-4c64-4e3f-b1d1-8dd55733a875)

### Throughput
---

![comparison_throughput](https://github.com/user-attachments/assets/1506091b-f29d-4526-a181-f2701b0b70a1)

**Comment by Ssukriti** [comment]
the investigation between transformers 4.40 and 4.,42 was conducted by IBM research and not found to be as significant of a difference as reported here. There is some degradation for sure, but it was stated that degradation is acceptable and we need new features from 4.42 , hence we cannot downgrade to 4.40.

@praveenj83 

if performance between 4.42 and 4.43 is similar, we have to accept and move ahead . 
4.43 and 4.44 is already proven as similar

**Comment by Ssukriti** [comment]
if there is any major degradation from 4.42 - 4.43 however its worth reporting

**Comment by Ssukriti** [comment]
the real issue with 1.2 image vs 1.1 image however, is how intermediate checkpoints are stored , which is being resolved over slack communication

**Comment by anhuong** [comment]
After much debugging, the issue appears to be in where the intermediate checkpoints are being saved. When it is saved to local disk it is much faster than saving over network to PVC mounted COS bucket. 1.1.0 used a local tempdir to save the intermediate checkpoints and copied the final checkpoint to the user specified output_dir. This was removed in 1.2.0 and thus caused the slowdown. There are ways around this such as only saving the final checkpoint or saving intermediate checkpoints to local filesystem or PVC mounted as local disk.

To confirm that the checkpoints being saved to a COS bucket is the issue, Will, Angel, and I collected data from tuning runs (note that all times I say COS bucket, this is a PVC mounted COS bucket):

llama 7b, 2 gpu, tone dataset, 10 epoch:
- 1.2.0 image with 1.2.0 accelerate_launch: 65min (write to COS bucket)
- 1.2.0 image with 1.1.0 accelerate_launch: 36 minutes (write to tempdir then copies COS bucket)
- 1.2.0 image with 1.2.0 accelerate_launch but output_dir=local file in config.json: 35 minutes

4 gpu, 5200 samples alpaca dataset, llama 13b chat, 1 epoch:
- 1.1.0 release image:
   - train_runtime: 16m17s --> faster saving to tempdir
   - total time: 31m34s --> takes longer to copy final checkpoint to output_dir
- 1.2.1 dev image save to COS bucket:
   - train_runtime: 31m51s --> takes longer saving to COS bucket
   - total time: 36m48s --> no longer copying checkpoint
- 1.2.1 dev image with saving to local directory (/app/mydir):
   - train_runtime: 18.5min --> faster bc checkpoints saved to local disk
   - total time: 20min
- 1.2.1 dev image with 1.1.0 accelerate_launch script and save to COS bucket:
   - train_runtime: 18.5min --> faster saving to tempdir
   - total time: 20m50s

Note that train_runtime only includes the time it took to train (which is the value RH is using to track) and total time includes pre and post-processing steps. Thus this matches the findings RH found and as you can see, saving to a COS bucket is what caused the increase in time.

**Comment by albertoperdomo2** [comment]
As per discussed in Slack, I'm adding the same plots but this time including the transformers version **4.42.0**. Find the plots below. 

## Train runtime
---
![fix_comparison_40gb_combined_4_42_0_train_runtime](https://github.com/user-attachments/assets/b3c09fc8-785f-4537-82d1-dcf33f22c6ab)

## GPU usage
---
![fix_comparison_40gb_combined_4_42_0_gpu_total_memory_usage_max](https://github.com/user-attachments/assets/529fc199-5423-4e99-9e58-d85ccdd7a825)

## Throughput
---
![fix_comparison_40gb_combined_4_42_0_train_tokens_per_second](https://github.com/user-attachments/assets/073e0563-5744-4e6e-84e7-5646cf9727d1)

As you can see, the train runtime is higher, the throughput is lower and the GPU is similar in some cases.

**Comment by albertoperdomo2** [comment]
As we discussed internally, the behavior reported in this issue is solved by using `save_strategy=no` with the corresponding `save_model_dir` argument. Therefore, I close this since with the correct configuration it behaves as expected. Thanks!
