### ISSUE TITLE
Add support for registering custom AIM metadata

### ISSUE THREAD

**Issue by VassilisVassiliadis** [foundation-model-stack/fms-hf-tuning#34]
**Issue**

As a user that is running a large finetuning campaign of runs I would like to annotate each individual run with metadata. This way I'll be able to query my AIM server for my finetuning experiments in the future.

**Done when**
- [ ] add new parameter `aim_metadata` to the train() method for optional metadata that fms-hf-tuning propagates to AIM
- [ ] commandline argument which can point to a `json` file with aim metadata

**Comment by dushyantbehl** [comment]
@VassilisVassiliadis this also can be closed now... 🥂
