### ISSUE TITLE
Update input args for sftTrainer

### ISSUE THREAD

**Issue by anhuong** [foundation-model-stack/fms-hf-tuning#36]
**Is your feature request related to a problem? Please describe.**
To be more inline with HF and have clearer input arguments, there are a few flags that can be updated but will cause breaking change for users. These are listed as `TODOs` in [fms-hf-tuning](https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/tuning/sft_trainer.py):
- `model_max_length` should be updated to `max_seq_length`
- `data_path` should be updated to `training_data_path` since we also have validation_data_path

**Comment by Ssukriti** [comment]
@anhuong we should do it this week before we make first wheel release to open source pip
