### ISSUE TITLE
Not passing `--peft_method` should fallback to a method which is *not* parameter efficient like full model param tuning

### ISSUE THREAD

**Issue by kmehant** [foundation-model-stack/fms-hf-tuning#48]
Currently, not setting `--peft_method` defaults to prompt tuning. However, intuitively, not passing `--peft_method` means not to use any parameter efficient method like LoRA and prompt tuning. Therefore, its good to fallback to full parameter tuning rather prompt tuning.

**Comment by Ssukriti** [comment]
I agree with this suggestion. Do you think you can contribute this too @kmehant ? We are making our first wheel release in a few days, would be good to have this change before that as its an API breaking change. We will wait for wheel release until this can be contributed.

**Comment by kmehant** [comment]
@Ssukriti Have raised a PR for this - https://github.com/foundation-model-stack/fms-hf-tuning/pull/100
