### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by Ssukriti** [foundation-model-stack/fms-hf-tuning#5]
**Description**

The repo is in need for unit tests so we can start enforcing tests to be contributed with every code contribution. In this issue we can add a simple unit test framework to the repository and some simple tests to get started . We also need to enable tests to run as part of every PR build. 

**Acceptance criteria**

1. Add unit tests framework to the repo - preferred pytorch
2. Tests organization in the repository - new folder called tests where we organize tests going forward
3. Add some simple unit tests as a good example (example given in comments)
4. Enable tests to run as part of every build

**Comment by chakrn** [comment]
Corresponding issue in internal repo: https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/555

**Comment by Ssukriti** [comment]
thanks @tedhtchang , you can refer to https://github.com/caikit/caikit-nlp as an example on how tests are organized. we also need to create a tests folder or some organization on where to keep tests in this repository

**Comment by tedhtchang** [comment]
@Ssukriti This is an output of the sample unit test. https://github.com/tedhtchang/fms-hf-tuning/actions/runs/8068469672/job/22041318467?pr=2
