### ISSUE TITLE
Create a Contributor/Developer.md

### ISSUE THREAD

**Issue by jbusche** [foundation-model-stack/fms-hf-tuning#55]
Add a CONTRIBUTING.md and/or DEVELOPER.md file to help new open source members get up to speed quickly.

One suggestion was to use the caikit [CONTRIBUTING.md](https://github.com/caikit/caikit/blob/main/CONTRIBUTING.md) file as a starting point.

**Comment by jbusche** [comment]
Some things that might need tweaks:

The new CODEOWNERS file might need different or additional people added
Right now there are no template(s) on new issues, but that's something that could be added later.
Development setup and unit testing will likely change soon due to issues https://github.com/foundation-model-stack/fms-hf-tuning/issues/5 and https://github.com/foundation-model-stack/fms-hf-tuning/issues/56

**Comment by Ssukriti** [comment]
thank you for the contribution :) this can be closed
