### ISSUE TITLE
Python package dependency management for building/development

### ISSUE THREAD

**Issue by jbusche** [foundation-model-stack/fms-hf-tuning#56]
There's a problem with the current [requirements.txt](https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/requirements.txt) method as it pulls in too many requirements for CI/CD.  We want to enable users to install minimal set of dependencies needed for functioning of the repository and to perform tuning techniques. Other dependencies should be optional. 

This issue is to explore what best optional dependency framework to use to ensure install is light-weight. 

Tasks include:
1. Explore how to enable optional dependencies - what are best practices open source repositories use
2. Add that framework to this repository with associated documentation

**Comment by Ssukriti** [comment]
some ideas from @hickeyma and Fabian is to use https://packaging.python.org/en/latest/specifications/pyproject-toml/

**Comment by hickeyma** [comment]
@jbusche There isn't a problems with requirements files per say. It is just that the implement optional dependencies using requirements files is clunky as you have to have separate files. The [Python packaging](https://packaging.python.org/en/latest/specifications/pyproject-toml/) provides a cleaner method where you can specify [optional dependencies](https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table).

**Comment by jbusche** [comment]
OK, added pr https://github.com/foundation-model-stack/fms-hf-tuning/pull/68 that hopefully addresses the issue...
