### ISSUE TITLE
Enable lint for PR

### ISSUE THREAD

**Issue by tedhtchang** [foundation-model-stack/fms-hf-tuning#59]
Enable lint and checks for every PR

**Comment by hickeyma** [comment]
@tedhtchang Formatting is already enabled: https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/.github/workflows/format.yml
Just need to call the linting as per the formatting pattern.

**Comment by tedhtchang** [comment]
@hickeyma I [ran pylint](https://github.com/tedhtchang/fms-hf-tuning/actions/runs/8068335609/job/22040844845?pr=1) in my repo. Got the following error:
```
-----------------------------------
Your code has been rated at 5.84/10

lint: exit 30 (2.25 seconds) /home/runner/work/fms-hf-tuning/fms-hf-tuning> pylint tuning 'scripts/*.py' pid=[206](https://github.com/tedhtchang/fms-hf-tuning/actions/runs/8068335609/job/22040844845?pr=1#step:6:207)5
.pkg: _exit> python /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  lint: FAIL code 30 (6.42=setup[4.17]+cmd[2.25] seconds)
  evaluation failed :( (6.48 seconds)
Error: Process completed with exit code 30.
```

**Comment by hickeyma** [comment]
@tedhtchang You need to fix the linting errors as part of the PR to enable linting for everyone. This way you provide a base that it fully listed that new PRs work from.
