### ISSUE TITLE
add validation dataset to train

### ISSUE THREAD

**Issue by Ssukriti** [foundation-model-stack/fms-hf-tuning#6]
**Description**

currently the train only accepts JSON file to a train dataset. We also need to add support for validation dataset to enable early stopping and possibly other features in the future

**Acceptance Criteria**
1. Accept validation dataset in train

**Comment by chakrn** [comment]
Corresponding issue in internal repo: https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/554

**Comment by chakrn** [comment]
Corresponding issue in internal repo: https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/555
