### ISSUE TITLE
Add load and inference functions

### ISSUE THREAD

**Issue by Ssukriti** [foundation-model-stack/fms-hf-tuning#7]
**Description**

Currently the repository has only train(). It would be good to add support for load and inference so tuned models can be validated with same repository

**Acceptance criteria**
1. Add ability to load tuned models / generative models
2. Add ability to run inference on those models
3. Add example scripts with each

**Comment by chakrn** [comment]
Corresponding issue in internal repo: https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/553

**Comment by Ssukriti** [comment]
done
