### ISSUE TITLE
Add unit tests for tuning.aim_loader

### ISSUE THREAD

**Issue by tedhtchang** [foundation-model-stack/fms-hf-tuning#71]
## Is your feature request related to a problem? Please describe.

Add unit tests for the tuning/aim_loader.py module.

## Describe the solution you'd like

If possible, each function should have test cases in the file tests/tuning/test_aim_loader.py
and pass test with the command `pytest tests/tuning/test_aim_loader.py`

## Additional context

Add any other context about the feature request here.

**Comment by Ssukriti** [comment]
@alex-jw-brooks when you get time, please comment if we need a unit test for this

**Comment by dushyantbehl** [comment]
@Ssukriti @alex-jw-brooks we do need unit test for this function as the underlying api is 3rd party and arguments are involved. I can happily add them as I wrote this first hand and am aware of the behavior.

**Comment by Ssukriti** [comment]
Thank you , yes please contribute . We are prioritizing reviews of unit tests before we add too much more code 🙂

**Comment by anhuong** [comment]
closing this issue as unit tests were added for AIM which is now in tracker https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/tests/trackers/test_aim_tracker.py
