### ISSUE TITLE
integrate black formatter

### ISSUE THREAD

**Issue by Ssukriti** [foundation-model-stack/fms-hf-tuning#8]
**Description**
To keep the code in good health and retain styling conventions, it is a good practice to integrate tools such as black formatter to the repo  https://black.readthedocs.io/en/stable/

**Acceptance criteria**
1. integrate black formatter
2. make sure it runs with every build as a check and build fails if formatter fails
3. Add it as a pre commit hook, so it checks on every commit https://stackoverflow.com/questions/71180810/python-black-code-formatter-is-there-any-way-to-apply-automatic-black-formatti

**Comment by chakrn** [comment]
Corresponding issue in internal repo: https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/552

**Comment by hickeyma** [comment]
Re-opening as formatter added in #31 but still need to hook into CI/CD.
